app:
  name: karthik kumar
  desc: welcome to ${app.name}

my:
  greeting: Hello Karthik
  list:
    values: one,two,three

dbValues:
    connection: karthik

#db.connection:{connectionString: `http://____`, username: `foo`, password: `pass`}
db:
  connection:
    connectionString: test.connection.string
    username: test-user
    password: test-pass
  host: 127.0.0.100
  port: 2400


management.endpoints.web.exposure.include: "*"