app:
    name: karthik kumar
    desc: welcome to ${app.name}

my:
    greeting: Hello Karthik
    list:
        values: one,two,three

dbValues:
    connection: karthik


#db.connection:{connectionString: `http://____`, username: `foo`, password: `pass`}
db:
    connection:
        connectionString: http://____
        username: karthik
        password: pass
    host: 127.0.0.1
    port: 1200


management.endpoints.web.exposure.include: "*"

spring.profiles.active: test